#include "instructions_x86.h"

instruction_t instruction_list_x86_ret[] = {
	{ INS_RET, 1, "\xC3"        , "RETN" },
	{ INS_RET, 3, "\xC2\x00\x00", "RETN 0" },
	{ INS_RET, 3, "\xC2\x01\x00", "RETN 1" },
	{ INS_RET, 3, "\xC2\x02\x00", "RETN 2" },
	{ INS_RET, 3, "\xC2\x03\x00", "RETN 3" },
	{ INS_RET, 3, "\xC2\x04\x00", "RETN 4" },
	{ INS_RET, 3, "\xC2\x08\x00", "RETN 8" },
	{ INS_RET, 3, "\xC2\x0C\x00", "RETN 0C" },
	{ INS_RET, 3, "\xC2\x10\x00", "RETN 10" },
	{ INS_RET, 3, "\xC2\x14\x00", "RETN 14" },
	{ INS_RET, 3, "\xC2\x18\x00", "RETN 18" },
	{ INS_RET, 3, "\xC2\x1C\x00", "RETN 1C" },
	{ INS_RET, 3, "\xC2\x20\x00", "RETN 20" },
	{ INS_RET, 3, "\xC2\x24\x00", "RETN 24" },
	{ INS_RET, 3, "\xC2\x28\x00", "RETN 28" },
	{ INS_RET, 3, "\xC2\x2C\x00", "RETN 2C" },
	{ INS_RET, 3, "\xC2\x30\x00", "RETN 30" },
	{ INS_DEBUG, 2, "\xEB\xFE", "JMP -2" },
	{ INS_DEBUG, 1, "\xCC", "INT 3" },
	{ INS_DEBUG, 2, "\xCD\x03", "INT 3" }
};

int ret_count = sizeof(instruction_list_x86_ret) / sizeof(instruction_list_x86_ret[0]);

instruction_t instruction_list_x86[] = {
	{ INS_POP, 1, "\x58", "POP EAX" },
	{ INS_POP, 1, "\x59", "POP ECX" },
	{ INS_POP, 1, "\x5A", "POP EDX" },
	{ INS_POP, 1, "\x5B", "POP EBX" },
	{ INS_POP, 1, "\x5C", "POP ESP" },
	{ INS_POP, 1, "\x5D", "POP EBP" },
	{ INS_POP, 1, "\x5E", "POP ESI" },
	{ INS_POP, 1, "\x5F", "POP EDI" },

	{ INS_MOV, 2, "\x8B\xC0", "MOV EAX,EAX" },
	{ INS_MOV, 2, "\x8B\xC1", "MOV EAX,ECX" },
	{ INS_MOV, 2, "\x8B\xC2", "MOV EAX,EDX" },
	{ INS_MOV, 2, "\x8B\xC3", "MOV EAX,EBX" },
	{ INS_MOV, 2, "\x8B\xC4", "MOV EAX,ESP" },
	{ INS_MOV, 2, "\x8B\xC5", "MOV EAX,EBP" },
	{ INS_MOV, 2, "\x8B\xC6", "MOV EAX,ESI" },
	{ INS_MOV, 2, "\x8B\xC7", "MOV EAX,EDI" },
	{ INS_MOV, 2, "\x8B\xC8", "MOV ECX,EAX" },
	{ INS_MOV, 2, "\x8B\xC9", "MOV ECX,ECX" },
	{ INS_MOV, 2, "\x8B\xCA", "MOV ECX,EDX" },
	{ INS_MOV, 2, "\x8B\xCB", "MOV ECX,EBX" },
	{ INS_MOV, 2, "\x8B\xCC", "MOV ECX,ESP" },
	{ INS_MOV, 2, "\x8B\xCD", "MOV ECX,EBP" },
	{ INS_MOV, 2, "\x8B\xCE", "MOV ECX,ESI" },
	{ INS_MOV, 2, "\x8B\xCF", "MOV ECX,EDI" },
	{ INS_MOV, 2, "\x8B\xD0", "MOV EDX,EAX" },
	{ INS_MOV, 2, "\x8B\xD1", "MOV EDX,ECX" },
	{ INS_MOV, 2, "\x8B\xD2", "MOV EDX,EDX" },
	{ INS_MOV, 2, "\x8B\xD3", "MOV EDX,EBX" },
	{ INS_MOV, 2, "\x8B\xD4", "MOV EDX,ESP" },
	{ INS_MOV, 2, "\x8B\xD5", "MOV EDX,EBP" },
	{ INS_MOV, 2, "\x8B\xD6", "MOV EDX,ESI" },
	{ INS_MOV, 2, "\x8B\xD7", "MOV EDX,EDI" },
	{ INS_MOV, 2, "\x8B\xD8", "MOV EBX,EAX" },
	{ INS_MOV, 2, "\x8B\xD9", "MOV EBX,ECX" },
	{ INS_MOV, 2, "\x8B\xDA", "MOV EBX,EDX" },
	{ INS_MOV, 2, "\x8B\xDB", "MOV EBX,EBX" },
	{ INS_MOV, 2, "\x8B\xDC", "MOV EBX,ESP" },
	{ INS_MOV, 2, "\x8B\xDD", "MOV EBX,EBP" },
	{ INS_MOV, 2, "\x8B\xDE", "MOV EBX,ESI" },
	{ INS_MOV, 2, "\x8B\xDF", "MOV EBX,EDI" },
	{ INS_MOV, 2, "\x8B\xE0", "MOV ESP,EAX" },
	{ INS_MOV, 2, "\x8B\xE1", "MOV ESP,ECX" },
	{ INS_MOV, 2, "\x8B\xE2", "MOV ESP,EDX" },
	{ INS_MOV, 2, "\x8B\xE3", "MOV ESP,EBX" },
	{ INS_MOV, 2, "\x8B\xE4", "MOV ESP,ESP" },
	{ INS_MOV, 2, "\x8B\xE5", "MOV ESP,EBP" },
	{ INS_MOV, 2, "\x8B\xE6", "MOV ESP,ESI" },
	{ INS_MOV, 2, "\x8B\xE7", "MOV ESP,EDI" },
	{ INS_MOV, 2, "\x8B\xE8", "MOV EBP,EAX" },
	{ INS_MOV, 2, "\x8B\xE9", "MOV EBP,ECX" },
	{ INS_MOV, 2, "\x8B\xEA", "MOV EBP,EDX" },
	{ INS_MOV, 2, "\x8B\xEB", "MOV EBP,EBX" },
	{ INS_MOV, 2, "\x8B\xEC", "MOV EBP,ESP" },
	{ INS_MOV, 2, "\x8B\xED", "MOV EBP,EBP" },
	{ INS_MOV, 2, "\x8B\xEE", "MOV EBP,ESI" },
	{ INS_MOV, 2, "\x8B\xEF", "MOV EBP,EDI" },
	{ INS_MOV, 2, "\x8B\xF0", "MOV ESI,EAX" },
	{ INS_MOV, 2, "\x8B\xF1", "MOV ESI,ECX" },
	{ INS_MOV, 2, "\x8B\xF2", "MOV ESI,EDX" },
	{ INS_MOV, 2, "\x8B\xF3", "MOV ESI,EBX" },
	{ INS_MOV, 2, "\x8B\xF4", "MOV ESI,ESP" },
	{ INS_MOV, 2, "\x8B\xF5", "MOV ESI,EBP" },
	{ INS_MOV, 2, "\x8B\xF6", "MOV ESI,ESI" },
	{ INS_MOV, 2, "\x8B\xF7", "MOV ESI,EDI" },
	{ INS_MOV, 2, "\x8B\xF8", "MOV EDI,EAX" },
	{ INS_MOV, 2, "\x8B\xF9", "MOV EDI,ECX" },
	{ INS_MOV, 2, "\x8B\xFA", "MOV EDI,EDX" },
	{ INS_MOV, 2, "\x8B\xFB", "MOV EDI,EBX" },
	{ INS_MOV, 2, "\x8B\xFC", "MOV EDI,ESP" },
	{ INS_MOV, 2, "\x8B\xFD", "MOV EDI,EBP" },
	{ INS_MOV, 2, "\x8B\xFE", "MOV EDI,ESI" },
	{ INS_MOV, 2, "\x8B\xFF", "MOV EDI,EDI" },
	{ INS_MOV, 2, "\x8D\x00", "LEA EAX,DWORD PTR DS:[EAX]" },
	{ INS_MOV, 2, "\x8D\x01", "LEA EAX,DWORD PTR DS:[ECX]" },
	{ INS_MOV, 2, "\x8D\x02", "LEA EAX,DWORD PTR DS:[EDX]" },
	{ INS_MOV, 2, "\x8D\x03", "LEA EAX,DWORD PTR DS:[EBX]" },
	{ INS_MOV, 2, "\x8D\x08", "LEA ECX,DWORD PTR DS:[EAX]" },
	{ INS_MOV, 2, "\x8D\x09", "LEA ECX,DWORD PTR DS:[ECX]" },
	{ INS_MOV, 2, "\x8D\x0A", "LEA ECX,DWORD PTR DS:[EDX]" },
	{ INS_MOV, 2, "\x8D\x0B", "LEA ECX,DWORD PTR DS:[EBX]" },
	{ INS_MOV, 2, "\x8D\x10", "LEA EDX,DWORD PTR DS:[EAX]" },
	{ INS_MOV, 2, "\x8D\x11", "LEA EDX,DWORD PTR DS:[ECX]" },
	{ INS_MOV, 2, "\x8D\x12", "LEA EDX,DWORD PTR DS:[EDX]" },
	{ INS_MOV, 2, "\x8D\x13", "LEA EDX,DWORD PTR DS:[EBX]" },
	{ INS_MOV, 2, "\x8D\x18", "LEA EBX,DWORD PTR DS:[EAX]" },
	{ INS_MOV, 2, "\x8D\x19", "LEA EBX,DWORD PTR DS:[ECX]" },
	{ INS_MOV, 2, "\x8D\x1A", "LEA EBX,DWORD PTR DS:[EDX]" },
	{ INS_MOV, 2, "\x8D\x1B", "LEA EBX,DWORD PTR DS:[EBX]" },
	{ INS_MOV, 1, "\x91", "XCHG EAX,ECX" },
	{ INS_MOV, 1, "\x92", "XCHG EAX,EDX" },
	{ INS_MOV, 1, "\x93", "XCHG EAX,EBX" },
	{ INS_MOV, 1, "\x94", "XCHG EAX,ESP" },
	{ INS_MOV, 1, "\x95", "XCHG EAX,EBP" },
	{ INS_MOV, 1, "\x96", "XCHG EAX,ESI" },
	{ INS_MOV, 1, "\x97", "XCHG EAX,EDI" },
	{ INS_MOV, 2, "\x87\xC9", "XCHG ECX,ECX" },
	{ INS_MOV, 2, "\x87\xD1", "XCHG ECX,EDX" },
	{ INS_MOV, 2, "\x87\xD9", "XCHG ECX,EBX" },
	{ INS_MOV, 2, "\x87\xE1", "XCHG ECX,ESP" },
	{ INS_MOV, 2, "\x87\xE9", "XCHG ECX,EBP" },
	{ INS_MOV, 2, "\x87\xF1", "XCHG ECX,ESI" },
	{ INS_MOV, 2, "\x87\xF9", "XCHG ECX,EDI" },
	{ INS_MOV, 2, "\x87\xCA", "XCHG EDX,ECX" },
	{ INS_MOV, 2, "\x87\xD2", "XCHG EDX,EDX" },
	{ INS_MOV, 2, "\x87\xDA", "XCHG EDX,EBX" },
	{ INS_MOV, 2, "\x87\xE2", "XCHG EDX,ESP" },
	{ INS_MOV, 2, "\x87\xEA", "XCHG EDX,EBP" },
	{ INS_MOV, 2, "\x87\xF2", "XCHG EDX,ESI" },
	{ INS_MOV, 2, "\x87\xFA", "XCHG EDX,EDI" },
	{ INS_MOV, 2, "\x87\xCB", "XCHG EBX,ECX" },
	{ INS_MOV, 2, "\x87\xD3", "XCHG EBX,EDX" },
	{ INS_MOV, 2, "\x87\xDB", "XCHG EBX,EBX" },
	{ INS_MOV, 2, "\x87\xE3", "XCHG EBX,ESP" },
	{ INS_MOV, 2, "\x87\xEB", "XCHG EBX,EBP" },
	{ INS_MOV, 2, "\x87\xF3", "XCHG EBX,ESI" },
	{ INS_MOV, 2, "\x87\xFB", "XCHG EBX,EDI" },
	{ INS_MOV, 2, "\x87\xCC", "XCHG ESP,ECX" },
	{ INS_MOV, 2, "\x87\xD4", "XCHG ESP,EDX" },
	{ INS_MOV, 2, "\x87\xDC", "XCHG ESP,EBX" },
	{ INS_MOV, 2, "\x87\xE4", "XCHG ESP,ESP" },
	{ INS_MOV, 2, "\x87\xEC", "XCHG ESP,EBP" },
	{ INS_MOV, 2, "\x87\xF4", "XCHG ESP,ESI" },
	{ INS_MOV, 2, "\x87\xFC", "XCHG ESP,EDI" },
	{ INS_MOV, 2, "\x87\xCD", "XCHG EBP,ECX" },
	{ INS_MOV, 2, "\x87\xD5", "XCHG EBP,EDX" },
	{ INS_MOV, 2, "\x87\xDD", "XCHG EBP,EBX" },
	{ INS_MOV, 2, "\x87\xE5", "XCHG EBP,ESP" },
	{ INS_MOV, 2, "\x87\xED", "XCHG EBP,EBP" },
	{ INS_MOV, 2, "\x87\xF5", "XCHG EBP,ESI" },
	{ INS_MOV, 2, "\x87\xFD", "XCHG EBP,EDI" },
	{ INS_MOV, 2, "\x87\xCE", "XCHG ESI,ECX" },
	{ INS_MOV, 2, "\x87\xD6", "XCHG ESI,EDX" },
	{ INS_MOV, 2, "\x87\xDE", "XCHG ESI,EBX" },
	{ INS_MOV, 2, "\x87\xE6", "XCHG ESI,ESP" },
	{ INS_MOV, 2, "\x87\xEE", "XCHG ESI,EBP" },
	{ INS_MOV, 2, "\x87\xF6", "XCHG ESI,ESI" },
	{ INS_MOV, 2, "\x87\xFE", "XCHG ESI,EDI" },
	{ INS_MOV, 2, "\x87\xCF", "XCHG EDI,ECX" },
	{ INS_MOV, 2, "\x87\xD7", "XCHG EDI,EDX" },
	{ INS_MOV, 2, "\x87\xDF", "XCHG EDI,EBX" },
	{ INS_MOV, 2, "\x87\xE7", "XCHG EDI,ESP" },
	{ INS_MOV, 2, "\x87\xEF", "XCHG EDI,EBP" },
	{ INS_MOV, 2, "\x87\xF7", "XCHG EDI,ESI" },
	{ INS_MOV, 2, "\x87\xFF", "XCHG EDI,EDI" },

	{ INS_ALTER, 1, "\x40", "INC EAX" },
	{ INS_ALTER, 1, "\x41", "INC ECX" },
	{ INS_ALTER, 1, "\x42", "INC EDX" },
	{ INS_ALTER, 1, "\x43", "INC EBX" },
	{ INS_ALTER, 1, "\x44", "INC ESP" },
	{ INS_ALTER, 1, "\x45", "INC EBP" },
	{ INS_ALTER, 1, "\x46", "INC ESI" },
	{ INS_ALTER, 1, "\x47", "INC EDI" },
	{ INS_ALTER, 1, "\x48", "DEC EAX" },
	{ INS_ALTER, 1, "\x49", "DEC ECX" },
	{ INS_ALTER, 1, "\x4A", "DEC EDX" },
	{ INS_ALTER, 1, "\x4B", "DEC EBX" },
	{ INS_ALTER, 1, "\x4C", "DEC ESP" },
	{ INS_ALTER, 1, "\x4D", "DEC EBP" },
	{ INS_ALTER, 1, "\x4E", "DEC ESI" },
	{ INS_ALTER, 1, "\x4F", "DEC EDI" },
	{ INS_ALTER, 2, "\x33\xC0", "XOR EAX,EAX" },
	{ INS_ALTER, 2, "\x33\xC9", "XOR ECX,ECX" },
	{ INS_ALTER, 2, "\x33\xD2", "XOR EDX,EDX" },
	{ INS_ALTER, 2, "\x33\xDB", "XOR EBX,EBX" },
	{ INS_ALTER, 2, "\x33\xE4", "XOR ESP,ESP" },
	{ INS_ALTER, 2, "\x33\xF6", "XOR ESI,ESI" },
	{ INS_ALTER, 2, "\x33\xFF", "XOR EDI,EDI" },
	{ INS_ALTER, 3, "\x66\x33\xC0", "XOR AX,AX" },
	{ INS_ALTER, 3, "\x66\x33\xC9", "XOR CX,CX" },
	{ INS_ALTER, 3, "\x66\x33\xD2", "XOR DX,DX" },
	{ INS_ALTER, 3, "\x66\x33\xDB", "XOR BX,BX" },
	{ INS_ALTER, 3, "\x66\x33\xE4", "XOR SP,SP" },
	{ INS_ALTER, 3, "\x66\x33\xED", "XOR BP,BP" },
	{ INS_ALTER, 3, "\x66\x33\xF6", "XOR SI,SI" },
	{ INS_ALTER, 3, "\x66\x33\xFF", "XOR DI,DI" },
	{ INS_ALTER, 2, "\x32\xC0", "XOR AL,AL" },
	{ INS_ALTER, 2, "\x32\xC9", "XOR CL,CL" },
	{ INS_ALTER, 2, "\x32\xD2", "XOR DL,DL" },
	{ INS_ALTER, 2, "\x32\xDB", "XOR BL,BL" },
	{ INS_ALTER, 2, "\x32\xE4", "XOR AH,AH" },
	{ INS_ALTER, 2, "\x32\xED", "XOR CH,CH" },
	{ INS_ALTER, 2, "\x32\xF6", "XOR DH,DH" },
	{ INS_ALTER, 2, "\x32\xFF", "XOR BH,BH" },

	{ INS_LOAD, 2, "\x8B\x00", "MOV EAX,DWORD PTR DS:[EAX]" },
	{ INS_LOAD, 2, "\x8B\x08", "MOV ECX,DWORD PTR DS:[EAX]" },
	{ INS_LOAD, 2, "\x8B\x10", "MOV EDX,DWORD PTR DS:[EAX]" },
	{ INS_LOAD, 2, "\x8B\x18", "MOV EBX,DWORD PTR DS:[EAX]" },
	{ INS_LOAD, 2, "\x8B\x20", "MOV ESP,DWORD PTR DS:[EAX]" },
	{ INS_LOAD, 2, "\x8B\x28", "MOV EBP,DWORD PTR DS:[EAX]" },
	{ INS_LOAD, 2, "\x8B\x30", "MOV ESI,DWORD PTR DS:[EAX]" },
	{ INS_LOAD, 2, "\x8B\x38", "MOV EDI,DWORD PTR DS:[EAX]" },
	{ INS_LOAD, 2, "\x8B\x01", "MOV EAX,DWORD PTR DS:[ECX]" },
	{ INS_LOAD, 2, "\x8B\x09", "MOV ECX,DWORD PTR DS:[ECX]" },
	{ INS_LOAD, 2, "\x8B\x11", "MOV EDX,DWORD PTR DS:[ECX]" },
	{ INS_LOAD, 2, "\x8B\x19", "MOV EBX,DWORD PTR DS:[ECX]" },
	{ INS_LOAD, 2, "\x8B\x21", "MOV ESP,DWORD PTR DS:[ECX]" },
	{ INS_LOAD, 2, "\x8B\x29", "MOV EBP,DWORD PTR DS:[ECX]" },
	{ INS_LOAD, 2, "\x8B\x31", "MOV ESI,DWORD PTR DS:[ECX]" },
	{ INS_LOAD, 2, "\x8B\x39", "MOV EDI,DWORD PTR DS:[ECX]" },
	{ INS_LOAD, 2, "\x8B\x02", "MOV EAX,DWORD PTR DS:[EDX]" },
	{ INS_LOAD, 2, "\x8B\x0A", "MOV ECX,DWORD PTR DS:[EDX]" },
	{ INS_LOAD, 2, "\x8B\x12", "MOV EDX,DWORD PTR DS:[EDX]" },
	{ INS_LOAD, 2, "\x8B\x1A", "MOV EBX,DWORD PTR DS:[EDX]" },
	{ INS_LOAD, 2, "\x8B\x22", "MOV ESP,DWORD PTR DS:[EDX]" },
	{ INS_LOAD, 2, "\x8B\x2A", "MOV EBP,DWORD PTR DS:[EDX]" },
	{ INS_LOAD, 2, "\x8B\x32", "MOV ESI,DWORD PTR DS:[EDX]" },
	{ INS_LOAD, 2, "\x8B\x3A", "MOV EDI,DWORD PTR DS:[EDX]" },
	{ INS_LOAD, 2, "\x8B\x03", "MOV EAX,DWORD PTR DS:[EBX]" },
	{ INS_LOAD, 2, "\x8B\x0B", "MOV ECX,DWORD PTR DS:[EBX]" },
	{ INS_LOAD, 2, "\x8B\x13", "MOV EDX,DWORD PTR DS:[EBX]" },
	{ INS_LOAD, 2, "\x8B\x1B", "MOV EBX,DWORD PTR DS:[EBX]" },
	{ INS_LOAD, 2, "\x8B\x23", "MOV ESP,DWORD PTR DS:[EBX]" },
	{ INS_LOAD, 2, "\x8B\x2B", "MOV EBP,DWORD PTR DS:[EBX]" },
	{ INS_LOAD, 2, "\x8B\x33", "MOV ESI,DWORD PTR DS:[EBX]" },
	{ INS_LOAD, 2, "\x8B\x3B", "MOV EDI,DWORD PTR DS:[EBX]" },
	{ INS_LOAD, 3, "\x8B\x04\x24", "MOV EAX,DWORD PTR SS:[ESP]" },
	{ INS_LOAD, 3, "\x8B\x0C\x24", "MOV ECX,DWORD PTR SS:[ESP]" },
	{ INS_LOAD, 3, "\x8B\x14\x24", "MOV EDX,DWORD PTR SS:[ESP]" },
	{ INS_LOAD, 3, "\x8B\x1C\x24", "MOV EBX,DWORD PTR SS:[ESP]" },
	{ INS_LOAD, 3, "\x8B\x24\x24", "MOV ESP,DWORD PTR SS:[ESP]" },
	{ INS_LOAD, 3, "\x8B\x2C\x24", "MOV EBP,DWORD PTR SS:[ESP]" },
	{ INS_LOAD, 3, "\x8B\x34\x24", "MOV ESI,DWORD PTR SS:[ESP]" },
	{ INS_LOAD, 3, "\x8B\x3C\x24", "MOV EDI,DWORD PTR SS:[ESP]" },
	{ INS_LOAD, 3, "\x8B\x45\x00", "MOV EAX,DWORD PTR SS:[EBP]" },
	{ INS_LOAD, 3, "\x8B\x4D\x00", "MOV ECX,DWORD PTR SS:[EBP]" },
	{ INS_LOAD, 3, "\x8B\x55\x00", "MOV EDX,DWORD PTR SS:[EBP]" },
	{ INS_LOAD, 3, "\x8B\x5D\x00", "MOV EBX,DWORD PTR SS:[EBP]" },
	{ INS_LOAD, 3, "\x8B\x65\x00", "MOV ESP,DWORD PTR SS:[EBP]" },
	{ INS_LOAD, 3, "\x8B\x6D\x00", "MOV EBP,DWORD PTR SS:[EBP]" },
	{ INS_LOAD, 3, "\x8B\x75\x00", "MOV ESI,DWORD PTR SS:[EBP]" },
	{ INS_LOAD, 3, "\x8B\x7D\x00", "MOV EDI,DWORD PTR SS:[EBP]" },
	{ INS_LOAD, 2, "\x8B\x06", "MOV EAX,DWORD PTR DS:[ESI]" },
	{ INS_LOAD, 2, "\x8B\x0E", "MOV ECX,DWORD PTR DS:[ESI]" },
	{ INS_LOAD, 2, "\x8B\x16", "MOV EDX,DWORD PTR DS:[ESI]" },
	{ INS_LOAD, 2, "\x8B\x1E", "MOV EBX,DWORD PTR DS:[ESI]" },
	{ INS_LOAD, 2, "\x8B\x26", "MOV ESP,DWORD PTR DS:[ESI]" },
	{ INS_LOAD, 2, "\x8B\x2E", "MOV EBP,DWORD PTR DS:[ESI]" },
	{ INS_LOAD, 2, "\x8B\x36", "MOV ESI,DWORD PTR DS:[ESI]" },
	{ INS_LOAD, 2, "\x8B\x3E", "MOV EDI,DWORD PTR DS:[ESI]" },
	{ INS_LOAD, 2, "\x8B\x07", "MOV EAX,DWORD PTR DS:[EDI]" },
	{ INS_LOAD, 2, "\x8B\x0F", "MOV ECX,DWORD PTR DS:[EDI]" },
	{ INS_LOAD, 2, "\x8B\x17", "MOV EDX,DWORD PTR DS:[EDI]" },
	{ INS_LOAD, 2, "\x8B\x1F", "MOV EBX,DWORD PTR DS:[EDI]" },
	{ INS_LOAD, 2, "\x8B\x27", "MOV ESP,DWORD PTR DS:[EDI]" },
	{ INS_LOAD, 2, "\x8B\x2F", "MOV EBP,DWORD PTR DS:[EDI]" },
	{ INS_LOAD, 2, "\x8B\x37", "MOV ESI,DWORD PTR DS:[EDI]" },
	{ INS_LOAD, 2, "\x8B\x3F", "MOV EDI,DWORD PTR DS:[EDI]" },

	{ INS_STORE, 2, "\x89\x00", "MOV DWORD PTR DS:[EAX],EAX" },
	{ INS_STORE, 2, "\x89\x08", "MOV DWORD PTR DS:[EAX],ECX" },
	{ INS_STORE, 2, "\x89\x10", "MOV DWORD PTR DS:[EAX],EDX" },
	{ INS_STORE, 2, "\x89\x18", "MOV DWORD PTR DS:[EAX],EBX" },
	{ INS_STORE, 2, "\x89\x20", "MOV DWORD PTR DS:[EAX],ESP" },
	{ INS_STORE, 2, "\x89\x28", "MOV DWORD PTR DS:[EAX],EBP" },
	{ INS_STORE, 2, "\x89\x30", "MOV DWORD PTR DS:[EAX],ESI" },
	{ INS_STORE, 2, "\x89\x38", "MOV DWORD PTR DS:[EAX],EDI" },
	{ INS_STORE, 2, "\x89\x01", "MOV DWORD PTR DS:[ECX],EAX" },
	{ INS_STORE, 2, "\x89\x09", "MOV DWORD PTR DS:[ECX],ECX" },
	{ INS_STORE, 2, "\x89\x11", "MOV DWORD PTR DS:[ECX],EDX" },
	{ INS_STORE, 2, "\x89\x19", "MOV DWORD PTR DS:[ECX],EBX" },
	{ INS_STORE, 2, "\x89\x21", "MOV DWORD PTR DS:[ECX],ESP" },
	{ INS_STORE, 2, "\x89\x29", "MOV DWORD PTR DS:[ECX],EBP" },
	{ INS_STORE, 2, "\x89\x31", "MOV DWORD PTR DS:[ECX],ESI" },
	{ INS_STORE, 2, "\x89\x39", "MOV DWORD PTR DS:[ECX],EDI" },
	{ INS_STORE, 2, "\x89\x02", "MOV DWORD PTR DS:[EDX],EAX" },
	{ INS_STORE, 2, "\x89\x0A", "MOV DWORD PTR DS:[EDX],ECX" },
	{ INS_STORE, 2, "\x89\x12", "MOV DWORD PTR DS:[EDX],EDX" },
	{ INS_STORE, 2, "\x89\x1A", "MOV DWORD PTR DS:[EDX],EBX" },
	{ INS_STORE, 2, "\x89\x22", "MOV DWORD PTR DS:[EDX],ESP" },
	{ INS_STORE, 2, "\x89\x2A", "MOV DWORD PTR DS:[EDX],EBP" },
	{ INS_STORE, 2, "\x89\x32", "MOV DWORD PTR DS:[EDX],ESI" },
	{ INS_STORE, 2, "\x89\x3A", "MOV DWORD PTR DS:[EDX],EDI" },
	{ INS_STORE, 2, "\x89\x03", "MOV DWORD PTR DS:[EBX],EAX" },
	{ INS_STORE, 2, "\x89\x0B", "MOV DWORD PTR DS:[EBX],ECX" },
	{ INS_STORE, 2, "\x89\x13", "MOV DWORD PTR DS:[EBX],EDX" },
	{ INS_STORE, 2, "\x89\x1B", "MOV DWORD PTR DS:[EBX],EBX" },
	{ INS_STORE, 2, "\x89\x23", "MOV DWORD PTR DS:[EBX],ESP" },
	{ INS_STORE, 2, "\x89\x2B", "MOV DWORD PTR DS:[EBX],EBP" },
	{ INS_STORE, 2, "\x89\x33", "MOV DWORD PTR DS:[EBX],ESI" },
	{ INS_STORE, 2, "\x89\x3B", "MOV DWORD PTR DS:[EBX],EDI" },
	{ INS_STORE, 3, "\x89\x04\x24", "MOV DWORD PTR SS:[ESP],EAX" },
	{ INS_STORE, 3, "\x89\x0C\x24", "MOV DWORD PTR SS:[ESP],ECX" },
	{ INS_STORE, 3, "\x89\x14\x24", "MOV DWORD PTR SS:[ESP],EDX" },
	{ INS_STORE, 3, "\x89\x1C\x24", "MOV DWORD PTR SS:[ESP],EBX" },
	{ INS_STORE, 3, "\x89\x24\x24", "MOV DWORD PTR SS:[ESP],ESP" },
	{ INS_STORE, 3, "\x89\x2C\x24", "MOV DWORD PTR SS:[ESP],EBP" },
	{ INS_STORE, 3, "\x89\x34\x24", "MOV DWORD PTR SS:[ESP],ESI" },
	{ INS_STORE, 3, "\x89\x3C\x24", "MOV DWORD PTR SS:[ESP],EDI" },
	{ INS_STORE, 3, "\x89\x45\x00", "MOV DWORD PTR SS:[EBP],EAX" },
	{ INS_STORE, 3, "\x89\x4D\x00", "MOV DWORD PTR SS:[EBP],ECX" },
	{ INS_STORE, 3, "\x89\x55\x00", "MOV DWORD PTR SS:[EBP],EDX" },
	{ INS_STORE, 3, "\x89\x5D\x00", "MOV DWORD PTR SS:[EBP],EBX" },
	{ INS_STORE, 3, "\x89\x65\x00", "MOV DWORD PTR SS:[EBP],ESP" },
	{ INS_STORE, 3, "\x89\x6D\x00", "MOV DWORD PTR SS:[EBP],EBP" },
	{ INS_STORE, 3, "\x89\x75\x00", "MOV DWORD PTR SS:[EBP],ESI" },
	{ INS_STORE, 3, "\x89\x7D\x00", "MOV DWORD PTR SS:[EBP],EDI" },
	{ INS_STORE, 2, "\x89\x06", "MOV DWORD PTR DS:[ESI],EAX" },
	{ INS_STORE, 2, "\x89\x0E", "MOV DWORD PTR DS:[ESI],ECX" },
	{ INS_STORE, 2, "\x89\x16", "MOV DWORD PTR DS:[ESI],EDX" },
	{ INS_STORE, 2, "\x89\x1E", "MOV DWORD PTR DS:[ESI],EBX" },
	{ INS_STORE, 2, "\x89\x26", "MOV DWORD PTR DS:[ESI],ESP" },
	{ INS_STORE, 2, "\x89\x2E", "MOV DWORD PTR DS:[ESI],EBP" },
	{ INS_STORE, 2, "\x89\x36", "MOV DWORD PTR DS:[ESI],ESI" },
	{ INS_STORE, 2, "\x89\x3E", "MOV DWORD PTR DS:[ESI],EDI" },
	{ INS_STORE, 2, "\x89\x07", "MOV DWORD PTR DS:[EDI],EAX" },
	{ INS_STORE, 2, "\x89\x0F", "MOV DWORD PTR DS:[EDI],ECX" },
	{ INS_STORE, 2, "\x89\x17", "MOV DWORD PTR DS:[EDI],EDX" },
	{ INS_STORE, 2, "\x89\x1F", "MOV DWORD PTR DS:[EDI],EBX" },
	{ INS_STORE, 2, "\x89\x27", "MOV DWORD PTR DS:[EDI],ESP" },
	{ INS_STORE, 2, "\x89\x2F", "MOV DWORD PTR DS:[EDI],EBP" },
	{ INS_STORE, 2, "\x89\x37", "MOV DWORD PTR DS:[EDI],ESI" },
	{ INS_STORE, 2, "\x89\x3F", "MOV DWORD PTR DS:[EDI],EDI" },
	{ INS_FIX_ESP, 3, "\x83\xC4\x01", "ADD ESP,1" },
	{ INS_FIX_ESP, 3, "\x83\xC4\x02", "ADD ESP,2" },
	{ INS_FIX_ESP, 3, "\x83\xC4\x03", "ADD ESP,3" },
	{ INS_FIX_ESP, 3, "\x83\xC4\x04", "ADD ESP,4" },
	{ INS_FIX_ESP, 3, "\x83\xC4\x08", "ADD ESP,8" },
	{ INS_FIX_ESP, 3, "\x83\xC4\x0C", "ADD ESP,0C" },
	{ INS_FIX_ESP, 3, "\x83\xC4\x10", "ADD ESP,10" },
	{ INS_FIX_ESP, 3, "\x83\xC4\x14", "ADD ESP,14" },
	{ INS_FIX_ESP, 3, "\x83\xC4\x18", "ADD ESP,18" },
	{ INS_FIX_ESP, 3, "\x83\xC4\x1C", "ADD ESP,1C" },
	{ INS_FIX_ESP, 3, "\x83\xC4\x20", "ADD ESP,20" },
	{ INS_FIX_ESP, 3, "\x83\xC4\x24", "ADD ESP,24" },
	{ INS_FIX_ESP, 3, "\x83\xC4\x28", "ADD ESP,28" },
	{ INS_FIX_ESP, 3, "\x83\xC4\x2C", "ADD ESP,2C" },
	{ INS_FIX_ESP, 3, "\x83\xC4\x30", "ADD ESP,30" }
};


int inst_count = sizeof(instruction_list_x86) / sizeof(instruction_list_x86[0]);
